---
label: Package
hide_body: false
fields:
- type: text
  name: title
  label: Title
  description: Package Name
- type: text
  label: Subtitle
  name: subtitle
  description: short description of package
- type: textarea
  name: journey-description
  label: journey description
  description: detailed description
- type: datetime
  name: start-date
  label: start date
  description: Start Date of journey
- type: datetime
  name: end-date
  label: End Date
  description: End Date of journey
- type: file
  name: image
  label: 'Main image '
  description: Add the header image here. This will be shown on the package details
    page.
- type: textarea
  label: Journey Guide
  name: journey_guide
  description: 'Details of Guide '
- type: file
  name: thumbnail
  label: thumbnail
  description: package thumbnail- smaller size of the original image
- type: file
  name: map_image
  label: Map image
  description: location map
- type: list
  name: journey-highlights
  label: Journey Highlight
  description: journey highlight
- type: list
  name: journey-experience
  label: Journey experience
  description: Journey experience
- type: boolean
  name: guided
  label: guided journey
  description: Guided yes or no
- type: boolean
  name: featured
  label: Featured
  description: " Setting this to true makes it visible on the home page."
- type: tag_list
  name: categories
  label: Categories
  description: package categories
- type: text
  name: excerpt_separator
  label: excerpt_separator
  description: "<!--more--> - use this..this is the small description that comes in
    your package summary"
  default: "<!--more-->"
  config:
    required: true
- type: text
  name: layout
  label: layout
  description: The layout for the packages is - package
  default: package
pages:
- _journeys/trek-to-holy-cave-of-shri-mahavatar-babaji.md
- _journeys/Navagraha-Temple-Pilgrimage.md
- _journeys/Enlightenment-Intensive-Retreat.md
- _journeys/Karmakshalan-Camp.md
- _journeys/abc.md
